### ISSUE TITLE
Rotated images

### ISSUE THREAD

**Issue by ironbone** [joomlaworks/simple-image-gallery#11]
Sometimes some of my images are displayed rotated. The thumbnails looks well. When opened from media or on my local computer they are ok

**Comment by fevangelou** [comment]
These images carry EXIF rotation data which are honored by desktop apps but they are not suitable for the web. You have to change the rotation manually.

Use this web service to check your images' EXIF data to verify that they carry rotation details on them: http://metapicz.com/
