### ISSUE TITLE
SIG 3.6.0 & PHP 7.4

### ISSUE THREAD

**Issue by mediafoks** [joomlaworks/simple-image-gallery#12]
Does not work on PHP 7.4
Error: Call to undefined function imagecreatefromjpeg()

**Comment by fevangelou** [comment]
You're missing the GD image library PHP module. Install it and it should work just fine.

If you don't control your hosting, ask whoever does to do so for you.

**Comment by mediafoks** [comment]
GD Support | enabled
GD Version | bundled (2.1.0 compatible)
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.8.0
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 6b
PNG Support | enabled
libPNG Version | 1.5.13
WBMP Support | enabled
XBM Support | enabled
WebP Support | enabled
