### ISSUE TITLE
Don't include Mootools

### ISSUE THREAD

**Issue by piotr-cz** [joomlaworks/simple-image-gallery#3]
Loading Mootools is not necessary ([sig.php@L201](https://github.com/joomlaworks/simple-image-gallery/blob/master/plugin/jw_sig.php#L201)) as it's not being used at all by this extension (I know it's being used by lightboxes in PRO version, but not here)..

This is extra important now, as Joomla 3.4 by itself almost never loads Mootools.

ps:
The [behaviour.js](https://github.com/joomlaworks/simple-image-gallery/blob/master/plugin/jw_sig/includes/js/behaviour.js) file is written in vanilla JS.

**Comment by fevangelou** [comment]
This is just a way to load our JS stuff *after* Mootools has loaded. This only applies to Joomla 1.5 of course.

**Comment by piotr-cz** [comment]
No, it actually loads MooTools always, see what [behaviour.framework](https://github.com/joomla/joomla-cms/blob/3.4.0/libraries/cms/html/behavior.php#L39) does.

I was curious to find out why MooTools is loading on my site so I've put a debug_backtrace() function in top of behaviour.framework and that's how I found referencing code in sig.php.

If it's supposed to load MooTools only in 1.5, then I'd change code to
```php
if (version_compare(JVERSION, '1.6.0', 'lt')) {
	JHTML::_('behavior.mootools');
}
```
