### ISSUE TITLE
error in joomla "tag" page

### ISSUE THREAD

**Issue by HarikalarKutusu** [joomlaworks/simple-image-gallery#4]
Error in Simple Image Gallery Free. Using J3.4.4 and latest SIG (plg_jw_sig-v3.0.1_j1.5-3.x)... This happens both when I click the tag or using a menu item to show articles with that tag. Otherwise the gallery is displayed fine.

Here is what I get:
( ! ) Fatal error: Call to a member function get() on a non-object in xxxxxxxxxx\plugins\content\jw_sig\jw_sig.php on line 117
Call Stack
# Time    Memory  Function    Location

1   0.0010  250304  {main}( )   ..\index.php:0
2   0.0780  3597216 JApplicationCms->execute( ) ..\index.php:45
3   0.0780  3597416 JApplicationSite->doExecute( )  ..\cms.php:252
4   0.3620  12439304    JApplicationSite->dispatch( )   ..\site.php:230
5   0.3640  12449632    JComponentHelper::renderComponent( )    ..\site.php:191
6   0.3870  12495528    JComponentHelper::executeComponent( )   ..\helper.php:372
7   0.3870  12516992    require_once( 'xxxxxx\components\com_tags\tags.php' )   ..\helper.php:392
8   0.4020  12797888    JControllerLegacy->execute( )   ..\tags.php:15
9   0.4020  12798032    TagsController->display( )  ..\legacy.php:728
10  0.4020  12800024    JControllerLegacy->display( )   ..\controller.php:52
11  0.4370  13540504    TagsViewTag->display( ) ..\legacy.php:690
12  0.6200  15239248    JEventDispatcher->trigger( )    ..\view.html.php:99
13  0.6200  15240288    JEvent->update( )   ..\dispatcher.php:160
14  0.6200  15241144    call_user_func_array:{xxxxxx\libraries\joomla\event\event.php:69} ( )   ..\event.php:69
15  0.6200  15241192    plgContentJw_sig->onContentPrepare( )   ..\event.php:69
16  0.6200  15241240    plgContentJw_sig->renderSimpleImageGallery( )   ..\jw_sig.php:42

This is the line:

// Control external parameters and set variable for controlling plugin layout within modules
if (!$params) $params = class_exists('JParameter') ? new JParameter(null) : new JRegistry(null);
$parsedInModule = $params->get('parsedInModule'); // ERROR LINE 117

**Comment by fevangelou** [comment]
Is this still valid for you?

**Comment by HarikalarKutusu** [comment]
Sorry, I have no idea in which website design this error surfaced, i.e. after two years... Probably either I removed the plugin or found a workaround at that time.

**Comment by fevangelou** [comment]
This code portion was updated either way, so it's probably not an issue anymore. Closing.
