### ISSUE TITLE
Deprecate PHP4 style constructors

### ISSUE THREAD

**Issue by Beryllium30** [joomlaworks/simple-image-gallery#8]
Getting an error rendered into administrator view and on the frontpage. 

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgContentJw_sig has a deprecated constructor in /xxx/plugins/content/jw_sig/jw_sig.php on line 18

**Comment by fevangelou** [comment]
Fixed with new 3.5.0 release.
