### ISSUE TITLE
Add git tags and github releases to each version in this repository

### ISSUE THREAD

**Issue by piotr-cz** [joomlaworks/simple-image-gallery#9]
So it's possible to download specific version or compare commits to master branch.

**Comment by fevangelou** [comment]
In the meantime, have a look at joomlaworks.net/downloads ;)

**Comment by piotr-cz** [comment]
Nice, but still to see changes I have to download two latest versions and diff manually

**Comment by fevangelou** [comment]
https://github.com/joomlaworks/simple-image-gallery/releases ;)

**Comment by piotr-cz** [comment]
Thank you
